import type { Metadata } from "next";
import {Outfit} from "next/font/google"
// @ts-ignore: allow global CSS side-effect import without declaration
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'
import Provider from "./Provider.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const CreateNewUser = () =>{
    
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={outfit.className}
        >
        <Provider>
          {children}
        </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
